language: objective-c  #1
osx_image: xcode7.2 #2
xcode_project: TravisCI.xcodeproj #3
xcode_scheme: TravisCI #4
xcode_sdk: iphonesimulator9.2 #5
before_install:
  - brew update
  - brew install swiftlint
  - brew install ruby
  - gem install --no-document saddler saddler-reporter-github
env:
  global:
   - secure: "WGEGID45v03GpHwdZEF8GUU/ZK70XzWaJ3NpikmUF8XxgV9ebdWhcRk3+57XAhj74436oFDDItT1jJM2gVXwGHEbd632rf4MRD0MSKU8dJ/Dpwf8kKiJNbEObxLIFnVDSVM7Y9LMU8uMutYFVp23c6e14HZlQfbKfXojh57mERI6zUJ+jx+rQWfMhNMmRbSuWDNkn2vU9QgR4PKWxsQ+AgggG1Kko1RWSOaPLnB1s/GJvKaDWOCzE/C76ISGBxbIuk9XOUdCRhEOTMHdlH33MQ35W3kEvX+bhmQG/kGt0QIkq9Jl9+RyN2qdVa89yZR8Z5AbD+9xkaaij+/RaK3SSJmxeaDN+Q1ByXSRoDPxGd29+Uh5aIb3I425ZcPEhEvDO+ZXEpOk9Xzup6uAs7W/PxrKZZUxWhm1SkDi3q0eHrcSGjOBbGFjghbyPYS8CADhYAtCZPM8gpWWOrCfe6VJ6fPMNZKh8Cfl+Jh8Y6BoIVbwOYA7v9HrEvLyKppIT/oll4nyDbmYDFpPdIZgpQj+g++LU5AqXgNqHbw+PmWL2s2ScCnSBd2a3rmX87rGj7gM+7sL0etNrxJoBZmyFlZYHItvaPSXaclzqmDUNrWhQJ+vGwBjOZ5L9Ntc92H8uXDGC/p9O3SWgJ1Mc1Hq5RyQd9ATzRMUkDanbvw4mhVuUqM="
   - secure: "4gT4kRKgvN6J17fRWMT8EU9jNqsuEyjBjyrkcEZby48Jz67QMb2QbIQkbtyGNsfJ9JRQuNMZmWb2kysrFH2HUe749NBz8itV9ZMY1pZjlv7wWA7m9ugHAhe9UWH/YgPgUuPexSD/JcjR6V0oaC6zSlkefXQ+eC9M/Y2Ebv1w3slNOn/edhKdFlrrnV3H3xHuowkknagOiZkJHLRYROGKfUc+777A2d74NgWMF1DM+zUIrMHUs4/FeMHAuAziSeIkJYz7ANkvTSMbskHiFiNm42GE3wmqcE6RRev+v/bRWi3TSYKV2sHR9sLpSYnj1m7s9Sa42myraoNx2lI5LPB/u3dw2XgnwwWj76JruIBYrwfrqXSJez5zMc3VFJ0ycIZTKhs33pHUTKh/n8RX38ylo2sFxAjJP/5s9yJ5g4SkURTdnsSGWiDxfra5Psn/YKJnx97XJXxuoH3gpaHMHJBC2OtvCRX/Z1HEZUaG048+0YovqbyYH7W3xRlWmAk2tR9UiPg7RHpr+6XFpyMQFKOuLjnT1I0TsbP22+tj1HInUetkzYZwewsQV6Mdljn4aKNoQDVvV+ZH9VwMUeQ3MHMY+JLfa4DIOnpEl8XMqq8/YZlm7B/KzTG9tO4e87SCI5j7dWo1NOEIVEn6y9TrLB4QFJp8s/A14PY8WOCF023t3qc="

before_script: 
- fastlane enable_crash_reporting 
- bundle exec fastlane analyze 